-  
  name: data base installation
  hosts: localhost
  tasks:
   - name: mysql installation
     yum:
      name: postgres
      state: latest
   - name: server start
     service:
       name: postgres
       state: started
       enabled: true
